version: '3.0'

services:
  hashicorp_vault:
    build:
      context: ./vault
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      # - "/Users/sejokim/desktop/volumes/vault/file:/vault/file"
      # - "/Users/sejokim/desktop/volumes/vault/logs:/vault/logs"
      # - "/Users/sejokim/desktop/volumes/vault/config:/vault/config"
      - "./volumes/vault/file:/vault/file"
      - "./volumes/vault/logs:/vault/logs"
      - "./volumes/vault/config:/vault/config"
      - "./volumes/certs:/vault/certs"

    environment:
      VAULT_ADDR: "https://hashicorp_vault:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - app_network

  django_node_app:
    build: .
    container_name: django_node_container
    ports:
      - 8443:8443
    networks:
      - app_network
    volumes:
      - static-volume:/backend/static
      - "./volumes/certs:/backend/certs"
    env_file:
      - ./.env
    environment:
    # DB
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
    # LOGSTASH
      LOG_KEY: ${LOG_KEY}
    # Hashicorp vault
      VAULT_URL: "https://hashicorp_vault:8200"
      VAULT_TOKEN: ${VAULT_TOKEN}
    # SMTP EMAIL
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    # Google, 42 Oauth
      GOOGLE_AUTHORIZE_API: ${GOOGLE_AUTHORIZE_API}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      STATE: ${STATE}
      INTRA42_AUTHORIZE_API: ${INTRA42_AUTHORIZE_API}
      INTRA42_TOKEN_API: ${INTRA42_TOKEN_API}
      INTRA42_CLIENT_ID: ${INTRA42_CLIENT_ID}
      INTRA42_CLIENT_SECRET: ${INTRA42_CLIENT_SECRET}
      INTRA42_REDIRECT_URI: ${INTRA42_REDIRECT_URI}
      INTRA42_USERINFO_API: ${INTRA42_USERINFO_API}
      DJANGO_SETTING_MODULE: "src.settings"

    depends_on:
      - hashicorp_vault

  nginx:
    build: ./nginx
    container_name: nginx_container
    volumes:
      - "./frontend:/usr/share/nginx/html"
      - static-volume:/usr/share/nginx/html/static
      - "./volumes/certs:/etc/nginx/certs"
      # - "/Users/sejokim/desktop/volumes/nginx/logs:/var/log/nginx"
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 443:443 # https 사용
    depends_on:
      - django_node_app
    networks:
      - app_network

  # elasticsearch:
  #   build:
  #     context: ./elk/elasticsearch
  #     dockerfile: Dockerfile
  #   volumes:
  #     - "/Users/sejokim/desktop/volumes/elasticsearch/data:/usr/share/elasticsearch/data"
  #     - "/Users/sejokim/desktop/volumes/elasticsearch/certs:/usr/share/elasticsearch/config/certs"
  #   environment:
  #     discovery.type : single-node
  #     ELASTIC_PW : ${ELASTIC_PW}
  #     ES_JAVA_OPTS: "-Xms2g -Xmx2g"
  #     ES_CERTS_PW: ${ES_CERTS_PW}
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   networks:
  #     - app_network

  #   # elasticsearch-setup-passwords interactive --url "https://localhost:9200" -E xpack.security.http.ssl.verification_mode=none

  # logstash:
  #   build: ./elk/logstash
  #   container_name: logstash_container
  #   environment:
  #     LS_JAVA_OPTS: "-Xms2g -Xmx2g"
  #     ELASTIC_PW: ${ELASTIC_PW}
  #     ES_CERTS_PW: ${ES_CERTS_PW}
  #   volumes:
  #     - "/Users/sejokim/desktop/volumes/elasticsearch/certs:/usr/share/logstash/config/certs"
  #     - "/Users/sejokim/desktop/volumes/nginx/logs:/usr/share/logstash/logs"
  #   ports:
  #     - 5333:5333
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - app_network

  # kibana:
  #   build: ./elk/kibana
  #   container_name: kibana_container
  #   volumes:
  #     - "/Users/sejokim/desktop/volumes/kibana/data:/usr/share/kibana/data"
  #     - "/Users/sejokim/desktop/volumes/elasticsearch/certs:/usr/share/kibana/config/certs"
  #   environment:
  #     ELASTICSEARCH_URL: https://elasticsearch:9200
  #     ELASTIC_PW: ${ELASTIC_PW}
  #     ES_CERTS_PW: ${ES_CERTS_PW}
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - app_network

volumes:
  static-volume:
  cert-volume:

networks:
  app_network:
    driver: bridge
