version: '3.0'

services:
  django_node_app:
    build: .
    container_name: django_node_container
    volumes:
      - "./volumes/app:/app"
    ports:
      - 8000:8000 #django
      - 3000:3000 #node.js
    networks:
      - app_network
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}


  nginx:
    build: ./nginx
    container_name: nginx_container
    volumes:
      - "./volumes/nginx:/etc/nginx/conf.d"
    ports:
      - 443:443 # https 사용
    depends_on:
      - django_node_app
    networks:
      - app_network

  elasticsearch:
    image: elasticsearch:8.11.3
    volumes:
      - "./volumes/elasticsearch/data:/usr/share/elasticsearch/data" # 수정된 경로
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - app_network

  logstash:
    build: ./elk/logstash
    container_name: logstash_container
    volumes:
      - "./volumes/logstash/config:/usr/share/logstash/config" # 수정된 경로
      - "./volumes/logstash/pipeline:/usr/share/logstash/pipeline" # 수정된 경로
    ports:
      - 5333:5333
    depends_on:
      - elasticsearch
    networks:
      - app_network

  # kibana:
  #   build: ./elk/kibana
  #   ports:
  #     - 5601:5601
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge