# Generated by Django 4.2.8 on 2024-02-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasualGameView',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mode', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'casual_game_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameRecordView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('mode', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'game_record_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RankGameView',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rank_game_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.PositiveSmallIntegerField(choices=[(0, '1vs1'), (1, 'casual_tournament'), (2, 'rank')])),
                ('title', models.CharField(blank=True, null=True)),
                ('password', models.CharField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'AVAILABLE_WAITING'), (1, 'FULL_WAITING'), (2, 'IN_GAME'), (3, 'FINISHED'), (4, 'DELETED')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('player2_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('playtime', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'results',
            },
        ),
    ]
