# Generated by Django 4.2.8 on 2024-02-05 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_player_player1_remove_player_player2_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='casualgameview',
            table='casualgameview',
        ),
        migrations.AlterModelTable(
            name='rankgameview',
            table='rankgameview',
        ),
    ]
