# Generated by Django 4.2.8 on 2024-01-29 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pingpong', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='twoplayergame',
            name='player1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twoplayergame',
            name='player2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twoplayergame',
            name='winner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='player1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_player1', to='pingpong.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='player2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_player2', to='pingpong.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament', to='pingpong.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='winner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_winner', to='pingpong.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_player2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player3_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_player3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player4_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_player4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customgameroom',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customgame',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='customgame',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room', to='pingpong.customgameroom'),
        ),
        migrations.AlterUniqueTogether(
            name='tournament',
            unique_together={('player1_id', 'player2_id', 'player3_id', 'player4_id')},
        ),
    ]
