# Generated by Django 4.2.8 on 2024-01-03 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pingpong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twoplayergame',
            name='player_1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twoplayergame',
            name='player_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='first_player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_result_as_first_player_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='second_player_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_result_as_second_player_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_result_as_tournament_id', to='pingpong.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='player_1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_game_as_player_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='player_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_game_as_player_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_game_as_tournament_id', to='pingpong.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='winner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_game_as_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tournament_as_player_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tournament_as_player_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_3_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tournament_as_player_3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_4_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Tournament_as_player_4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customroom',
            name='manager_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customgame',
            name='player_1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_game_as_player_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customgame',
            name='player_2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_game_as_player_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customgame',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room', to='pingpong.customroom'),
        ),
        migrations.AddField(
            model_name='customgame',
            name='winner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_game_as_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
