# Generated by Django 4.2.8 on 2024-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_1vs1_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_tournament_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rank_wins',
            field=models.IntegerField(default=0),
        ),
    ]
