# Generated by Django 4.2.8 on 2024-01-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_code_sent_at_user_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='code_sent_at',
        ),
    ]
