name: CI

on:
  pull_request:
    branches: [main]
    types: [opened, edited, synchronize]

jobs:
  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commit Checker
        uses: agenthunt/conventional-commit-checker-action@v2.0.0
            
